version: '3.7'
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    hostname: traefik
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    networks:
    - default
    
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  rpui:
    container_name: rpui
    hostname: rpui
    restart: always  # optional
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
    - 9080:9080
    environment:
    - SERVER_LISTENPORT=9080
    # - KAFKA_BROKERS=redpanda:29092
    - CONFIG_FILEPATH=/etc/redpanda/console-config.yaml
    volumes:
    - ./setup/infra/redpanda-console-config.yaml:/etc/redpanda/console-config.yaml
    - ./proto/:/etc/protos
    depends_on:
    - redpanda
    - traefik
    networks:
    - default
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=frontend"
    - "traefik.http.routers.rpui.rule=(Host(`rpui.localhost`))"
    - "traefik.http.routers.rpui.entrypoints=web"


  redpanda:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    hostname: redpanda
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    ports:
    - 9092:9092
    networks:
    - default
    labels:
    - "traefik.enable=false"

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432
    networks:
    - default
    labels:
    - "traefik.enable=false"

  pgweb:
    container_name: pgweb  # optional
    hostname: pgweb
    restart: always  # optional
    image: sosedoff/pgweb
    ports: 
    - "8081:8081" 
    environment:
    - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
    - postgres
    - traefik
    networks:
    - default
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.pgweb.rule=(Host(`pgweb.localhost`))"
    - "traefik.http.routers.pgweb.entrypoints=web"
  
networks:
  default:
